import { chromium } from 'playwright';
const B = 'http://localhost:4332';
const P = '_dbg2';
const api = (u, m='GET', b) => fetch(B+u, b===undefined?{method:m}:{method:m,headers:{'content-type':'application/json'},body:JSON.stringify(b)}).then(r=>r.json());
console.log(await api('/api/project/new','POST',{name:P}));
const br = await chromium.launch();
const p = await br.newPage({ viewport: { width: 1500, height: 900 } });
p.on('pageerror', e => console.log('ERR', e.message));
p.on('console', m => console.log(m.type(), m.text().slice(0,200)));
await p.goto(B); await p.waitForTimeout(1000);
console.log('projects:', await p.evaluate(()=>[...document.querySelectorAll('#project option')].map(o=>o.value)));
await p.selectOption('#project', P); await p.waitForTimeout(1200);
await p.click('#btnNewCode'); await p.waitForTimeout(2000);
console.log('stage html:', (await p.evaluate(()=>document.querySelector('#stage').innerHTML)).slice(0,300));
console.log('what:', await p.textContent('#what'));
await p.evaluate(c=>document.querySelector('.CodeMirror').CodeMirror.setValue(c), "shape({width:400,height:200,background:'#fff'}).at(300,300);");
await p.waitForTimeout(2500);
console.log('stage html2:', (await p.evaluate(()=>document.querySelector('#stage').innerHTML)).slice(0,300));
console.log('what2:', await p.textContent('#what'));
console.log('codeErr:', await p.textContent('#codeErr'));
await br.close();
