import { chromium } from 'playwright';
import { pathToFileURL } from 'url';
import { lit, bounds } from './png.mjs';
const SP = 'C:/Users/allen/AppData/Local/Temp/claude/C--dev-graphics-channel/ed495a7a-f020-46b1-842d-a9b9efac922b/scratchpad/';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 900, height: 500 } });
p.on('console', m => console.log('  console:', m.text()));
p.on('pageerror', e => console.log('  ERR:', e.message));
await p.goto(pathToFileURL(SP + 'probe.html').href);
const shot = async n => { const buf = await p.locator('#stage').screenshot({ path: n ? SP + n : undefined }); return buf; };
const show = async (label, name) => {
  const buf = await shot(name);
  console.log(label.padEnd(20), 'lit=' + String(lit(buf)).padEnd(8), JSON.stringify(bounds(buf)));
};
await show('unmasked');
await p.evaluate(() => probe('world'));
await show('world coords', 'm-world.png');
await p.evaluate(() => probe('local'));
await show('local coords', 'm-local.png');
await p.evaluate(() => camera(true));
await show('camera + local', 'm-cam.png');
await p.evaluate(() => { camera(false); boxTransform('translate3d(150px,0,0)'); });
await show('el translated', 'm-eltx.png');
await b.close();
